### ISSUE TITLE
Add test that after closing the tab there is always a save with a comment

### ISSUE THREAD

**Issue by kulla** [serlo/ece-as-a-service#176]

**Comment by LarsTheGlidingSquirrel** [comment]
This is hard to test using Cypress. Gave us errors about unhandled rejected promises that made the tests fail. 
We also decided to change the implementation: Instead of trying to save the document in window.onbeforeunload, we check if there are pending changes and if so, display a confirmation. Reason: onbeforeunload is not guaranteed to be triggered, see: https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/

**Comment by kulla** [comment]
With https://github.com/serlo/ece-as-a-service/pull/211/commits/38952c9d6e8c9a10642c3f4fdfff8be46979fe60 we can actually implement and test this
